#!/bin/sh
RPI_LIB_LOC="../raspberry-pi"
RPI_DEST="drone"
RPI_NAME="pi@pidrone"


mkdir deployed
mkdir deployed/src
mkdir deployed/bin

cp -r main deployed
cp -r src deployed
cp -r $RPI_LIB_LOC/src deployed
cp -r include deployed
cp -r server deployed
cp -r client deployed
cp makefile deployed/makefile

# scp -r $SPI_LIB_LOC/* $RPI_NAME:$RPI_DEST
scp -r deployed/* $RPI_NAME:$RPI_DEST

rm -rf deployed